// Mocks generated by Mockito 5.4.6 from annotations
// in ownurtime/test/features/mood/domain/check_mood_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ownurtime/features/mood/domain/entities/mood_check.dart' as _i2;
import 'package:ownurtime/features/mood/domain/repositories/mood_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMoodCheck_0 extends _i1.SmartFake implements _i2.MoodCheck {
  _FakeMoodCheck_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MoodRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoodRepository extends _i1.Mock implements _i3.MoodRepository {
  MockMoodRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.MoodCheck> saveMoodCheck(
    String? userId,
    int? level, {
    String? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveMoodCheck,
              [userId, level],
              {#sessionId: sessionId},
            ),
            returnValue: _i4.Future<_i2.MoodCheck>.value(
              _FakeMoodCheck_0(
                this,
                Invocation.method(
                  #saveMoodCheck,
                  [userId, level],
                  {#sessionId: sessionId},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.MoodCheck>);

  @override
  _i4.Future<List<_i2.MoodCheck>> getTodayMoodChecks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodayMoodChecks, [userId]),
            returnValue: _i4.Future<List<_i2.MoodCheck>>.value(
              <_i2.MoodCheck>[],
            ),
          )
          as _i4.Future<List<_i2.MoodCheck>>);
}
